### ISSUE TITLE
Cifar exception in tensor size at beginning of training

### ISSUE THREAD

**Issue by david-klindt** [jhjacobsen/pytorch-i-revnet#13]
In utils_cifar.py line 105 (and 133):
train_loss += loss.data[0]

gives an error:
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by jhjacobsen** [comment]
Yes, the repo is based on an earlier pytorch version, would be great if you can do a pull request if you have made it run with a recent version.
