### ISSUE TITLE
About model size of i-RevNet (b)

### ISSUE THREAD

**Issue by djiajunustc** [jhjacobsen/pytorch-i-revnet#19]
Hi:

As illustrated in Table 1 of your ICLR 2018 paper, the number of parameters of i-RevNet (b) is 29M.
However, when I took the released iRevNet.py in this repository and compute the model size, I found the size I've get is different from that in the paper.
The number of paramters of this medel I've get is about 125.12MB, which is significantly larger than the supposed size. 
And the tool I take for model size computing is from https://github.com/Lyken17/pytorch-OpCounter.
I feel puzzled about the model size. Could you help me make it clear?

Best Regards,
Jiajun Deng

**Comment by djiajunustc** [comment]
I think the difference is due to the kernel size in each i-revblock.
The kernel size in this paper is 1X1 3X3 1X1, while the implementation of this repository is 3X3 3X3 3X3.

**Comment by jhjacobsen** [comment]
Yes, the experiments in the paper were done in a Tensorflow codebase but I reimplemented everything in Pytorch afterwards for release. In the process of that I discovered a few tiny improvements, nothing that would change the conclusions of the paper though.
