### ISSUE TITLE
Question: memory saving

### ISSUE THREAD

**Issue by tartavull** [jhjacobsen/pytorch-i-revnet#4]
Thanks for open sourcing your code and congrats on the paper!

From the paper:
"For the same reasons as in Gomez et al. (2017), our scheme also allows
avoiding storing any intermediate activations at training time, making memory consumption for very
deep i-RevNets not an issue in practice.

I was wondering where in the code was this happening, I was expecting some backward functions implementing this.

Thank you,
Ignacio

**Comment by jhjacobsen** [comment]
Hi Ignacio, we do not implement this here as it wasn't necessary for our experiments. But it is certainly possible!

Check out the Revnet TF code: https://github.com/renmengye/revnet-public
And for Pytorch this might be interesting for you as well (haven't tried it myself): https://github.com/silvandeleemput/memcnn
