### ISSUE TITLE
The size of tensor are not identifed

### ISSUE THREAD

**Issue by chouqin3** [jhjacobsen/pytorch-i-revnet#5]
when I run the code in the github, such as
import torch
from torch.autograd import Variable
from models.iRevNet import iRevNet

model = iRevNet(nBlocks=[6, 16, 72, 6], nStrides=[2, 2, 2, 2],
                nChannels=None, nClasses=1000, init_ds=2,
                dropout_rate=0., affineBN=True, in_shape=[3, 224, 224],
                mult=4)
y = model(Variable(torch.randn(1, 3, 32, 32)))
print(y.size())   
The errors are:
y1 = Fx2 + x1
RuntimeError: The size of tensor a (6) must match the size of tensor b (24) at non-singleton dimension 1
When debug it, I found the shape of Fx2 is 1X6X8X8, the shape of x1 is 1X24X8X8, how to fix it, please help.

**Comment by jhjacobsen** [comment]
You have to [specify the number of channels](https://github.com/jhjacobsen/pytorch-i-revnet/blob/master/scripts/train_cifar-10.sh)
