### ISSUE TITLE
Potential bug in model_utils.py

### ISSUE THREAD

**Issue by danfeiX** [jhjacobsen/pytorch-i-revnet#6]
Thanks for the great work. I think I found a potential bug in your code

https://github.com/jhjacobsen/pytorch-i-revnet/blob/master/models/model_utils.py#L36

Shouldn't it be `return x[:, :x.size(1) - self.pad_size, :, :]`?

**Comment by jhjacobsen** [comment]
Thanks for reporting the issue, you are right and I'll fix it!
Just for the record: It does not affect the reported results.
