### ISSUE TITLE
Inverse function has zero block size for final psi function initialization

### ISSUE THREAD

**Issue by ThorJonsson** [jhjacobsen/pytorch-i-revnet#7]
The issue refers to this line in the code.
https://github.com/jhjacobsen/pytorch-i-revnet/blob/c21afaebca0c7dd81c17c0c2ddf1e19979fa5448/models/iRevNet.py#L146

When using the code as is for CIFAR10, I get a ZeroDivisionError when computing the inverse.

This is due to a call to a psi function that has an invalid initialisation, i.e. self.init_ds = 0.

If I comment out this line the inverse seems to be computed correctly.

Really cool work by the way!

**Comment by jhjacobsen** [comment]
Thanks, fixed now!
